[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@uniswap/=node_modules/@uniswap/",
    "@layerzerolabs/=node_modules/@layerzerolabs/"
]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
ethereum = "https://eth.llamarpc.com"
sepolia = "${SEPOLIA_RPC_URL}"

