[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.30"
via_ir = true
optimizer = true
optimizer_runs = 200

# Remappings for LayerZero and other deps
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "@chainlink/=node_modules/@chainlink/",
    "@uniswap/=node_modules/@uniswap/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "hardhat/=node_modules/hardhat/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "base64-sol/=node_modules/base64-sol/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@axelar-network/=node_modules/@axelar-network/"
]

[profile.default.fuzz]
runs = 256

[profile.ci]
via_ir = true
optimizer = true
optimizer_runs = 200

